version: "3"

services:
  log-analysis:
    build: ./log-analysis
    volumes:
      - ./proto/:/proto
    container_name: log-analysis
    ports:
      - "50051:50051"
    depends_on:
      - alert-storing
  log-aggregator:
    build: ./log-aggregator
    volumes:
      - ./proto/:/proto
    container_name: log-aggregator
    depends_on:
      - log-analysis
    command: ["./wait-for-it.sh", "log-analysis:50051", "--", "python", "log-aggregator.py"]
  alert-storing:
    build: ./alert-storing
    volumes:
      - ./proto/:/proto
    container_name: alert-storing
    ports:
      - "50052:50052"
    depends_on:
      - email-server
      - redis 
  email-server:
    build: ./email-server
    volumes:
      - ./proto/:/proto
    container_name: email-server
    ports:
      - "50053:50053"
  web-logs:
    build: ./web-logs
    container_name: web-logs
    ports:
      - "8080:5000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
