# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app.proto',
  package='loganalysis',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapp.proto\x12\x0bloganalysis\"\x8c\x01\n\x03Log\x12\x11\n\tipAddress\x18\x01 \x01(\t\x12\x15\n\rtimeProcessed\x18\x02 \x01(\t\x12\x0f\n\x07request\x18\x03 \x01(\t\x12\x12\n\nstatusCode\x18\x04 \x01(\t\x12\x12\n\nobjectSize\x18\x05 \x01(\x03\x12\x0f\n\x07referer\x18\x06 \x01(\t\x12\x11\n\tuserAgent\x18\x07 \x01(\t\"\x1d\n\x06Result\x12\x13\n\x0b\x62lacklisted\x18\x01 \x01(\x08\x32\x44\n\x0bLogAnalysis\x12\x35\n\nAnalyseLog\x12\x10.loganalysis.Log\x1a\x13.loganalysis.Result\"\x00\x62\x06proto3')
)




_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='loganalysis.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ipAddress', full_name='loganalysis.Log.ipAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeProcessed', full_name='loganalysis.Log.timeProcessed', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='loganalysis.Log.request', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='loganalysis.Log.statusCode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objectSize', full_name='loganalysis.Log.objectSize', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referer', full_name='loganalysis.Log.referer', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userAgent', full_name='loganalysis.Log.userAgent', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=167,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='loganalysis.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blacklisted', full_name='loganalysis.Result.blacklisted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(
  DESCRIPTOR = _LOG,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:loganalysis.Log)
  ))
_sym_db.RegisterMessage(Log)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:loganalysis.Result)
  ))
_sym_db.RegisterMessage(Result)



_LOGANALYSIS = _descriptor.ServiceDescriptor(
  name='LogAnalysis',
  full_name='loganalysis.LogAnalysis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=200,
  serialized_end=268,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyseLog',
    full_name='loganalysis.LogAnalysis.AnalyseLog',
    index=0,
    containing_service=None,
    input_type=_LOG,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGANALYSIS)

DESCRIPTOR.services_by_name['LogAnalysis'] = _LOGANALYSIS

# @@protoc_insertion_point(module_scope)
